name: Merge

on:
  push:
    branches:
      - master

jobs:
  deploy_flatpak:
    name: Deploy Flatpak
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:7-${{ matrix.arch }}
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU for aarch64 emulation
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: mail.flatpak
          manifest-path: io.elementary.mail.json
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          branch: daily
          arch: ${{ matrix.arch }}

      - name: Deploy
        uses: flatpak/flatpak-github-actions/flat-manager@v6
        with:
          repository: appcenter
          flat-manager-url: https://flatpak-api.elementary.io
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}

  gettext:
    name: Gettext
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:7.2-x86_64
      options: --privileged

    steps:
    - name: Install git, python3-git and jq
      run: |
        apt-get update
        apt-get install git jq python3-git -y

    - name: Clone repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Update Translation Files
      uses: elementary/actions/gettext-flatpak@main
      with:
        manifest-path: 'io.elementary.mail.json'
      env:
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
